# Assigment 1


In [9]:
import numpy as np

Program to find maximum value and minimum value form the given matrix

In [10]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print("first matrix =")
print(a)
print("dimension of the matrix a=",a.ndim)
max=np.max(a)
min=np.min(a)
print('min value of the matrix a=',min)
print('max value of the matrix a=',max)



first matrix =
[[1 2 3 4]
 [5 6 7 8]]
dimension of the matrix a= 2
min value of the matrix a= 1
max value of the matrix a= 8


using logic

In [11]:
def max_val(a):
  max=a[0][0]
  min=a[0][0]
  for i in a:
    for j in i:
      if j>max:
        max=j
        if j<min:
          min=j
print("max val of a=",max)
print("min val of a=",min)

max val of a= 8
min val of a= 1


2. Program to perform following operations on the given matrix  
a. Find the number of rows and columns of a given matrix using NumPy             
b. Find the sum of values in a matrix

In [12]:
rows,columns=a.shape
sum=np.sum(a)
print("rows and columns",rows,",",columns)
print("sum of the matrix a=",sum)

rows and columns 2 , 4
sum of the matrix a= 36


In [13]:
# logic for the sum of  the matrix
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
c=0
print(np.sum(a))
for i in a:
  for j in i:
    c=c+j
print("sum of the matrix a=",c)

55
sum of the matrix a= 55


3. Program to perform following operations on 3x3 matrix:                  
a. addition of two matrices               
b. Subtraction of two matrices

In [14]:
matrix_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
matrix_4=np.array([[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
print("first matrix =")
print(matrix_3)
print("second matrix =")
print(matrix_4)
print("addition =")
print(matrix_3+matrix_4)
print("substraction =")
print(matrix_4 - matrix_3)


first matrix =
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
second matrix =
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
addition =
[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]
substraction =
[[[12 12 12]
  [12 12 12]]

 [[12 12 12]
  [12 12 12]]]


In [15]:
addition = np.zeros(matrix_3.shape, dtype=int)
subtraction = np.zeros(matrix_3.shape, dtype=int)

for i in range(matrix_3.shape[0]):
    for j in range(matrix_3.shape[1]):
        for k in range(matrix_3.shape[2]):
            addition[i][j][k] = matrix_3[i][j][k] + matrix_4[i][j][k]
            subtraction[i][j][k] = matrix_4[i][j][k] - matrix_3[i][j][k]

print("Addition of matrices:")
print(addition)
print("Subtraction of  matrices:")
print(subtraction)

Addition of matrices:
[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]
Subtraction of  matrices:
[[[12 12 12]
  [12 12 12]]

 [[12 12 12]
  [12 12 12]]]


4. Program to perform following operations on 1D array                    
a. Count the frequency of unique values in NumPy array?                           
b. Convert the matrix into a list         
c. Replace negative value with zero in numpy array

In [16]:

arr = np.array([1, 5, 12, 3, -14, -4, 5])
# a. Count the frequency of unique values in NumPy array
unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values and their counts:", dict(zip(unique_values, counts)))

# b. Convert the matrix into a list
arr_list = arr.tolist()
print("Converted array to list:", arr_list)

# c. Replace negative value with zero in NumPy array
arr[arr < 0] = 0
print("Array after replacing negative values with zero:", arr)

Unique values and their counts: {-14: 1, -4: 1, 1: 1, 3: 1, 5: 2, 12: 1}
Converted array to list: [1, 5, 12, 3, -14, -4, 5]
Array after replacing negative values with zero: [ 1  5 12  3  0  0  5]


In [17]:
def analyze_array(arr):
    unique, counts = np.unique(arr, return_counts=True)

    array_as_list = arr.tolist()

    replaced_array = np.where(arr < 0, 0, arr).tolist()

    print("Unique values:", unique.tolist())
    print("Frequency of unique values:", counts.tolist())
    print("Array as a list:", array_as_list)
    print("Array after replacing negative values with zero:", replaced_array)

analyze_array(arr)


Unique values: [0, 1, 3, 5, 12]
Frequency of unique values: [2, 1, 1, 2, 1]
Array as a list: [1, 5, 12, 3, 0, 0, 5]
Array after replacing negative values with zero: [1, 5, 12, 3, 0, 0, 5]


5. Program to perform statistical operations on the given array.            
a. Compute the median of the flattened NumPy array                               
b. Find Mean of  Numpy Array                 
c. Compute the variance of the NumPy array

In [18]:
median = np.median(arr)
mean = np.mean(arr)
variance = np.var(arr)
std_dev = np.std(arr)
print("Median of the flattened array:", median)
print("Mean of the array:", mean)
print("Variance of the array:", variance)
print("Standard deviation of the array:", std_dev)

Median of the flattened array: 3.0
Mean of the array: 3.7142857142857144
Variance of the array: 15.3469387755102
Standard deviation of the array: 3.9175169145148816


In [19]:
sorted_array = sorted(arr)
n = len(sorted_array)

# Mean
mean_value = np.sum(arr) / n

# Variance
variance = np.sum((arr - mean_value) ** 2) / n

# Standard Deviation
std_dev = variance ** 0.5

print('Mean =', mean_value)
print('Variance =', variance)
print('Standard Deviation =', std_dev)


Mean = 3.7142857142857144
Variance = 15.3469387755102
Standard Deviation = 3.9175169145148816


6. Create a 5X2 integer array from a range between 100 to 200 such that the
difference between each element is 10

In [20]:
np.arange(100, 200, 10).reshape(5, 2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

7.Following is the provided numPy array. Return array of item by taking   the third column from all rows                 


In [ ]:
a= np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
third_column = a[:, 2]
print("Third column from all rows:", third_column)