In [4]:
import numpy as np

In [9]:
a=np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [21]:
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("b=",b)
print("c=",c)

b= [[1 2 3]
 [4 5 6]]
c= [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
#get the dimension of the array
a.ndim


1

In [18]:
b.ndim

2

In [22]:
c.ndim

3

In [26]:
# geting the shape
a.dtype
b.dtype
c.dtype



dtype('int32')

In [30]:
# get size

a.itemsize
b.itemsize
c.itemsize

4

In [33]:
#get total size
a.size * a.itemsize
a.nbytes



24


In [34]:
b.nbytes

24

In [35]:
c.size * c.itemsize

48

In [36]:
c.nbytes

48